#!/bin/python3

#PurgeLog

import shutil # For copy file
import os     #For get file size # Check if file exist
import sys    #For CLI Arguments

# Lesson-4-Script_LogClear.py mylog.txt 10 5
if (len(sys.argv) < 4):
    print('Missing arguments: Usage is script.py 10 5')
    exit(1)

file_name  = sys.argv[1]
limitsize  = int(sys.argv[2])
logsnumber = int(sys.argv[3])

"""Check if MAIN file exist"""
if os.path.isfile(file_name):
    logfile_size = os.stat(file_name).st_size     #Get FileSize in Bytes
    logfile_size = logfile_size / 1024            #Convert from B to kB


    if logfile_size >= limitsize:
        if logsnumber > 0:
            for currentFileNum in range(logsnumber, 1, -1):
                src = file_name + '_' + str(currentFileNum - 1)
                dst = file_name + '_' + str(currentFileNum)
                if os.path.isfile(src):
                    shutil.copyfile(src, dst)
                    print('Copied: ' + src + 'to' + dst)
            shutil.copyfile(file_name, file_name + '_1')
            print('Copied: ' + file_name + ' to ' + file_name + '_1')
    myfile = open(file_name, 'w')
    myfile.close()
